# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'View/form_operacao_manual.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_formManual(object):
    def setupUi(self, formManual):
        formManual.setObjectName("formManual")
        formManual.resize(1020, 600)
        self.btVoltar = QtWidgets.QPushButton(formManual)
        self.btVoltar.setGeometry(QtCore.QRect(860, 510, 131, 71))
        self.btVoltar.setObjectName("btVoltar")
        self.label = QtWidgets.QLabel(formManual)
        self.label.setGeometry(QtCore.QRect(50, 50, 161, 51))
        self.label.setObjectName("label")
        self.btElevadorSobe = QtWidgets.QPushButton(formManual)
        self.btElevadorSobe.setGeometry(QtCore.QRect(370, 50, 84, 54))
        self.btElevadorSobe.setObjectName("btElevadorSobe")
        self.btElevadorDesce = QtWidgets.QPushButton(formManual)
        self.btElevadorDesce.setGeometry(QtCore.QRect(610, 50, 84, 54))
        self.btElevadorDesce.setObjectName("btElevadorDesce")
        self.label_2 = QtWidgets.QLabel(formManual)
        self.label_2.setGeometry(QtCore.QRect(50, 180, 261, 51))
        self.label_2.setObjectName("label_2")
        self.txSetPointQuente = QtWidgets.QLineEdit(formManual)
        self.txSetPointQuente.setGeometry(QtCore.QRect(370, 190, 131, 31))
        self.txSetPointQuente.setObjectName("txSetPointQuente")
        self.txTemperaturaQuente = QtWidgets.QLineEdit(formManual)
        self.txTemperaturaQuente.setGeometry(QtCore.QRect(590, 190, 113, 30))
        self.txTemperaturaQuente.setObjectName("txTemperaturaQuente")
        self.label_3 = QtWidgets.QLabel(formManual)
        self.label_3.setGeometry(QtCore.QRect(370, 160, 68, 22))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(formManual)
        self.label_4.setGeometry(QtCore.QRect(590, 160, 101, 22))
        self.label_4.setObjectName("label_4")
        self.btLigaQuente = QtWidgets.QPushButton(formManual)
        self.btLigaQuente.setGeometry(QtCore.QRect(740, 170, 64, 64))
        self.btLigaQuente.setObjectName("btLigaQuente")
        self.btDesligaQuente = QtWidgets.QPushButton(formManual)
        self.btDesligaQuente.setGeometry(QtCore.QRect(840, 170, 64, 64))
        self.btDesligaQuente.setObjectName("btDesligaQuente")
        self.label_5 = QtWidgets.QLabel(formManual)
        self.label_5.setGeometry(QtCore.QRect(590, 320, 101, 22))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(formManual)
        self.label_6.setGeometry(QtCore.QRect(370, 320, 68, 22))
        self.label_6.setObjectName("label_6")
        self.txTemperaturaFrio = QtWidgets.QLineEdit(formManual)
        self.txTemperaturaFrio.setGeometry(QtCore.QRect(590, 350, 113, 30))
        self.txTemperaturaFrio.setObjectName("txTemperaturaFrio")
        self.txSetPointFrio = QtWidgets.QLineEdit(formManual)
        self.txSetPointFrio.setGeometry(QtCore.QRect(370, 350, 131, 31))
        self.txSetPointFrio.setObjectName("txSetPointFrio")
        self.btLigaFrio = QtWidgets.QPushButton(formManual)
        self.btLigaFrio.setGeometry(QtCore.QRect(740, 330, 64, 64))
        self.btLigaFrio.setObjectName("btLigaFrio")
        self.btDesligaFrio = QtWidgets.QPushButton(formManual)
        self.btDesligaFrio.setGeometry(QtCore.QRect(840, 330, 64, 64))
        self.btDesligaFrio.setObjectName("btDesligaFrio")
        self.label_7 = QtWidgets.QLabel(formManual)
        self.label_7.setGeometry(QtCore.QRect(50, 340, 261, 51))
        self.label_7.setObjectName("label_7")

        self.retranslateUi(formManual)
        QtCore.QMetaObject.connectSlotsByName(formManual)

    def retranslateUi(self, formManual):
        _translate = QtCore.QCoreApplication.translate
        formManual.setWindowTitle(_translate("formManual", "Tela Manual"))
        self.btVoltar.setText(_translate("formManual", "Voltar"))
        self.label.setText(_translate("formManual", "<html><head/><body><p><span style=\" font-size:28pt; font-weight:600;\">Elevador</span></p></body></html>"))
        self.btElevadorSobe.setText(_translate("formManual", "Sobe"))
        self.btElevadorDesce.setText(_translate("formManual", "Desce"))
        self.label_2.setText(_translate("formManual", "<html><head/><body><p><span style=\" font-size:28pt; font-weight:600;\">Câmara quente</span></p></body></html>"))
        self.label_3.setText(_translate("formManual", "Set point"))
        self.label_4.setText(_translate("formManual", "Temperatura"))
        self.btLigaQuente.setText(_translate("formManual", "Liga"))
        self.btDesligaQuente.setText(_translate("formManual", "Desliga"))
        self.label_5.setText(_translate("formManual", "Temperatura"))
        self.label_6.setText(_translate("formManual", "Set point"))
        self.btLigaFrio.setText(_translate("formManual", "Liga"))
        self.btDesligaFrio.setText(_translate("formManual", "Desliga"))
        self.label_7.setText(_translate("formManual", "<html><head/><body><p><span style=\" font-size:28pt; font-weight:600;\">Câmara fria</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    formManual = QtWidgets.QWidget()
    ui = Ui_formManual()
    ui.setupUi(formManual)
    formManual.show()
    sys.exit(app.exec_())
